In [1]:
# import libraries
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_score, recall_score, accuracy_score, roc_auc_score, precision_recall_curve, f1_score, roc_curve
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import StandardScaler

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

%config InlineBackend.figure_formats = ['svg']  # or 'retina'
%matplotlib inline

sns.set(context='notebook', style='whitegrid')

In [2]:
diabetes_updated_df = pd.read_csv("Diabetes_Update_Df.csv")

# Change in Medication (Train)

In [3]:
X_change = diabetes_updated_df[['num_medications']]
y_change = diabetes_updated_df[['change']]

In [4]:
X_change.head()

num_medications
0                1
1               18
2               13
3               16
4                8

In [5]:
y_change.head()

change
0       0
1       1
2       0
3       1
4       1

In [6]:
# Train_test_split
X_change_train, X_change_test, y_change_train, y_change_test = train_test_split(X_change, y_change,test_size=0.2, random_state=42)

X_change1_train, X_Change1_val, y_change1_train, y_Change1_val = train_test_split(X_change_train, y_change_train, test_size=0.2, random_state=1)

In [7]:
np.mean(y_change_train)

change    0.462549
dtype: float64

In [8]:
np.mean(X_change1_train)

num_medications    16.010594
dtype: float64

In [9]:
# X_change1_train, y_change1_train
logr = LogisticRegression(C=1000)
logr.fit(X_change1_train, y_change1_train)

/Users/edk/anaconda3/envs/metis/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


LogisticRegression(C=1000)

In [10]:
logr.score(X_change1_train, y_change1_train)

0.6030953952924196

In [11]:
logr.coef_, logr.intercept_

(array([[0.06814164]]), array([-1.23585812]))

In [12]:
# precision_score and recall_score 
y_predict = logr.predict(X_change1_train)
print ("Precision: {:6.4f}, Recall: {:6.4f}".format(precision_score(y_change1_train, y_predict), recall_score(y_change1_train, y_predict)))

Precision: 0.6066, Recall: 0.4059


In [13]:
# F1 precision_score(y_change1_train, y_predict), recall_score(y_change1_train, y_predict)

# recall (y_true)
recall = y_change1_train

# predict (y_pred)
predict = y_predict

# calculate F1 score
f1_score(recall, predict)

0.48636941662692734

In [14]:
# Random Forest for num_medications and change
from sklearn.ensemble import RandomForestClassifier
RC = RandomForestClassifier(n_estimators = 100)
RC.fit(X_change1_train, y_change1_train)
y_RC_TRAIN_predict = RC.predict(X_change1_train)

print("Accuracy:",metrics.accuracy_score(y_change1_train, y_RC_TRAIN_predict))

/var/folders/0b/2h06wtt932j8vbn2kb4_x_2w0000gn/T/ipykernel_3934/468486237.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  RC.fit(X_change1_train, y_change1_train)


Accuracy: 0.606396536105268


# Test (Change in medication)

In [15]:
# X_change_test, y_change_test
logr = LogisticRegression(C=1000)
logr.fit(X_change_test, y_change_test)

/Users/edk/anaconda3/envs/metis/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


LogisticRegression(C=1000)

In [16]:
logr.score(X_change_test, y_change_test)

0.6033212145032918

In [17]:
logr.coef_, logr.intercept_

(array([[0.06682389]]), array([-1.23408662]))

In [18]:
# F1 
y_predict_test = logr.predict(X_change_test)
# recall (y_true)
recall = y_change_test

# predict (y_pred)
predict = y_predict_test

# calculate F1 score
f1_score(recall, predict)

0.48756029449098764

In [19]:
# Random Forest for num_medications and change
from sklearn.ensemble import RandomForestClassifier
RC = RandomForestClassifier(n_estimators = 100)
RC.fit(X_change_test, y_change_test)
y_RC_predict = RC.predict(X_change_test)

print("Accuracy:",metrics.accuracy_score(y_change_test, y_RC_predict))

/var/folders/0b/2h06wtt932j8vbn2kb4_x_2w0000gn/T/ipykernel_3934/332524231.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  RC.fit(X_change_test, y_change_test)


Accuracy: 0.6062690380269234


# Age (Train)

In [20]:
X_Diab_Med_age = diabetes_updated_df[['num_medications']]
y_Diab_Med_age = diabetes_updated_df[['age']]

In [21]:
# train_test_split (X = num_medications and number_diagnoses) and (y = age)
X_Diab_Med_age_train, X_Diab_Med_age_test, y_Diab_Med_age_train, y_Diab_Med_age_test = train_test_split(X_Diab_Med_age,y_Diab_Med_age,test_size=0.2, random_state=42)

X_DiabMed_age_train, X_DiabMed_age_val, y_DiabMed_age_train, y_DiabMed_age_val = train_test_split(X_Diab_Med_age_train, y_Diab_Med_age_train, test_size=0.2, random_state=1)

In [22]:
# Logistic Regression for 'age' X_DiabMed_age_train, y_DiabMed_age_train
logr = LogisticRegression(C=1000)
logr.fit(X_DiabMed_age_train, y_DiabMed_age_train)

/Users/edk/anaconda3/envs/metis/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/edk/anaconda3/envs/metis/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(C=1000)

In [23]:
logr.score(X_DiabMed_age_train, y_DiabMed_age_train)

0.25773464969522025

In [24]:
logr.coef_, logr.intercept_

(array([[-0.36298633],
        [-0.15791634],
        [-0.01863859],
        [ 0.0543413 ],
        [ 0.08099257],
        [ 0.09573347],
        [ 0.10309165],
        [ 0.09211125],
        [ 0.07440828],
        [ 0.03886275]]),
 array([-0.02844144, -0.05724823, -0.45611962, -0.62502099, -0.08671742,
         0.24489273,  0.39239061,  0.72682492,  0.5900939 , -0.70065447]))

In [40]:
# precision_score and recall_score X_DiabMed_age_train, y_DiabMed_age_train
y_predict = logr.predict(X_DiabMed_age_train)
print ("Precision: {:6.4f}, Recall: {:6.4f}".format(precision_score(y_DiabMed_age_train, y_predict, average = 'micro'), recall_score(y_DiabMed_age_train, y_predict, average = 'micro')))

Precision: 0.2574, Recall: 0.2574


In [31]:
# F1 precision_score(y_change1_train, y_predict), recall_score(y_change1_train, y_predict)

# recall (y_true)
recall = y_DiabMed_age_train

# predict (y_pred)
predict = y_predict

# calculate F1 score
f1_score(recall, predict, average = 'micro')

0.25773464969522025

In [32]:
f1_score(recall, predict, average = 'macro')

0.051930341562030545

In [33]:
f1_score(recall, predict, average = 'weighted')

0.12848275291530342

In [34]:
f1_score(recall, predict, average = None)

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.11750141, 0.40180201, 0.        , 0.        ])

In [35]:
# Random Forest for num_medications and change X_DiabMed_age_train, y_DiabMed_age_train
from sklearn.ensemble import RandomForestClassifier
RC = RandomForestClassifier(n_estimators = 100)
RC.fit(X_DiabMed_age_train, y_DiabMed_age_train)
y_RC_TRAIN_predict = RC.predict(X_DiabMed_age_train)

print("Accuracy:",metrics.accuracy_score(y_DiabMed_age_train, y_RC_TRAIN_predict))

/var/folders/0b/2h06wtt932j8vbn2kb4_x_2w0000gn/T/ipykernel_3934/3136663871.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  RC.fit(X_DiabMed_age_train, y_DiabMed_age_train)


Accuracy: 0.25951573031982683


# Age (Test)

In [36]:
# Logistic Regression for 'age' # X_Diab_Med_age_test, y_Diab_Med_age_test
logr = LogisticRegression(C=1000)
logr.fit(X_Diab_Med_age_test, y_Diab_Med_age_test)

/Users/edk/anaconda3/envs/metis/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/edk/anaconda3/envs/metis/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(C=1000)

In [37]:
logr.score(X_Diab_Med_age_test, y_Diab_Med_age_test)

0.2566080377321411

In [38]:
logr.coef_, logr.intercept_

(array([[-0.33359874],
        [-0.1557661 ],
        [-0.02313986],
        [ 0.0523579 ],
        [ 0.0767466 ],
        [ 0.08608273],
        [ 0.09836324],
        [ 0.08684171],
        [ 0.07202474],
        [ 0.04008779]]),
 array([-0.10642159, -0.05168506, -0.47224556, -0.679956  , -0.09434433,
         0.3953519 ,  0.43728697,  0.76120106,  0.59735053, -0.78653793]))

In [41]:
# precision_score and recall_score X_Diab_Med_age_test, y_Diab_Med_age_test
y_predict = logr.predict(X_Diab_Med_age_test)
print ("Precision: {:6.4f}, Recall: {:6.4f}".format(precision_score(y_Diab_Med_age_test, y_predict, average = 'micro'), recall_score(y_Diab_Med_age_test, y_predict, average = 'micro')))

Precision: 0.2566, Recall: 0.2566


In [42]:
# F1 precision_score(y_change1_train, y_predict), recall_score(y_change1_train, y_predict)

# recall (y_true)
recall = y_Diab_Med_age_test

# predict (y_pred)
predict = y_predict

# calculate F1 score
f1_score(recall, predict, average = 'micro')

0.2566080377321411

In [43]:
# Random Forest for  X_Diab_Med_age_test, y_Diab_Med_age_test
from sklearn.ensemble import RandomForestClassifier
RC = RandomForestClassifier(n_estimators = 100)
RC.fit(X_Diab_Med_age_test, y_Diab_Med_age_test)
y_RC_predict = RC.predict(X_Diab_Med_age_test)

print("Accuracy:",metrics.accuracy_score(y_Diab_Med_age_test, y_RC_predict))

/var/folders/0b/2h06wtt932j8vbn2kb4_x_2w0000gn/T/ipykernel_3934/2108502202.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  RC.fit(X_Diab_Med_age_test, y_Diab_Med_age_test)


Accuracy: 0.2614228161540729


# Gender (Train)

In [44]:
X_Diab_Med_gender = diabetes_updated_df[['num_medications']]
y_Diab_Med_gender = diabetes_updated_df[['gender']]

In [45]:
# train_test_split (X = num_medications and number_diagnoses) and (y = gender)
X_Diab_Med_gender_train, X_Diab_Med_gender_test, y_Diab_Med_gender_train, y_Diab_Med_gender_test = train_test_split(X_Diab_Med_gender,y_Diab_Med_gender,test_size=0.2, random_state=42)

X_DiabMed_gender_train, X_DiabMed_gender_val, y_DiabMed_gender_train, y_DiabMed_gender_val = train_test_split(X_Diab_Med_gender_train, y_Diab_Med_gender_train, test_size=0.2, random_state=1)

In [46]:
X_DiabMed_gender_train.head()

num_medications
40985               22
38441               14
42042               18
69887               14
73154               15

In [47]:
y_DiabMed_gender_train.head()


gender
40985     0.0
38441     1.0
42042     1.0
69887     1.0
73154     1.0

In [48]:
np.mean(y_DiabMed_gender_train)

gender    0.464294
dtype: float64

In [49]:
np.mean(X_DiabMed_gender_train)

num_medications    16.010594
dtype: float64

In [50]:
# Logistic Regression for 'gender' X_DiabMed_gender_train, y_DiabMed_gender_train
logr = LogisticRegression(C=1000)
logr.fit(X_DiabMed_gender_train, y_DiabMed_gender_train)

/Users/edk/anaconda3/envs/metis/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


LogisticRegression(C=1000)

In [51]:
logr.score(X_DiabMed_gender_train, y_DiabMed_gender_train)

0.5357060602803666

In [52]:
logr.coef_, logr.intercept_

(array([[-0.00565664]]), array([-0.05258559]))

In [56]:
# precision_score and recall_score X_DiabMed_gender_train, y_DiabMed_gender_train
y_predict = logr.predict(X_DiabMed_gender_train)
print ("Precision: {:6.4f}, Recall: {:6.4f}".format(precision_score(y_DiabMed_gender_train, y_predict), recall_score(y_DiabMed_gender_train, y_predict)))

Precision: 0.0000, Recall: 0.0000


/Users/edk/anaconda3/envs/metis/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [54]:
# F1 precision_score(y_change1_train, y_predict), recall_score(y_change1_train, y_predict)

# recall (y_true)
recall = y_DiabMed_gender_train

# predict (y_pred)
predict = y_predict

# calculate F1 score
f1_score(recall, predict)

0.0

In [57]:
# Random Forest for gender X_DiabMed_gender_train, y_DiabMed_gender_train
from sklearn.ensemble import RandomForestClassifier
RC = RandomForestClassifier(n_estimators = 100)
RC.fit(X_DiabMed_gender_train, y_DiabMed_gender_train)
y_RC_TRAIN_predict = RC.predict(X_DiabMed_gender_train)

print("Accuracy:",metrics.accuracy_score(y_DiabMed_gender_train, y_RC_TRAIN_predict))

/var/folders/0b/2h06wtt932j8vbn2kb4_x_2w0000gn/T/ipykernel_3934/2595381653.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  RC.fit(X_DiabMed_gender_train, y_DiabMed_gender_train)


Accuracy: 0.5402969491317232


# Gender (Test)

In [58]:
# Logistic Regression for 'gender' # X_Diab_Med_gender_test, y_Diab_Med_gender_test
logr = LogisticRegression(C=1000)
logr.fit(X_Diab_Med_gender_test, y_Diab_Med_gender_test)

/Users/edk/anaconda3/envs/metis/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


LogisticRegression(C=1000)

In [59]:
logr.score(X_Diab_Med_gender_test, y_Diab_Med_gender_test)

0.5389112705119387

In [60]:
logr.coef_, logr.intercept_

(array([[-0.00558275]]), array([-0.06630128]))

In [61]:
# precision_score and recall_score # X_Diab_Med_gender_test, y_Diab_Med_gender_test
y_predict = logr.predict(X_Diab_Med_gender_test)
print ("Precision: {:6.4f}, Recall: {:6.4f}".format(precision_score(y_Diab_Med_gender_test, y_predict), recall_score(y_Diab_Med_gender_test, y_predict)))

Precision: 0.0000, Recall: 0.0000


/Users/edk/anaconda3/envs/metis/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [62]:
# F1 precision_score(y_change1_train, y_predict), recall_score(y_change1_train, y_predict)

# recall (y_true)
recall = y_Diab_Med_gender_test

# predict (y_pred)
predict = y_predict

# calculate F1 score
f1_score(recall, predict)

0.0

In [63]:
# Random Forest for  # X_Diab_Med_gender_test, y_Diab_Med_gender_test
from sklearn.ensemble import RandomForestClassifier
RC = RandomForestClassifier(n_estimators = 100)
RC.fit(X_Diab_Med_gender_test, y_Diab_Med_gender_test)
y_RC_predict = RC.predict(X_Diab_Med_gender_test)

print("Accuracy:",metrics.accuracy_score(y_Diab_Med_gender_test, y_RC_predict))

/var/folders/0b/2h06wtt932j8vbn2kb4_x_2w0000gn/T/ipykernel_3934/96092769.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  RC.fit(X_Diab_Med_gender_test, y_Diab_Med_gender_test)


Accuracy: 0.5473616979463496


# Race (Train)

In [65]:
X_Diab_Med_race = diabetes_updated_df[['race']]

y_Diab_Med_race  = diabetes_updated_df[['num_medications']]

In [66]:
# train_test_split (X = num_medications and number_diagnoses) and (y = race)
X_Diab_Med_race_train, X_Diab_Med_race_test, y_Diab_Med_race_train, y_Diab_Med_race_test = train_test_split(X_Diab_Med_race,y_Diab_Med_race,test_size=0.2, random_state=42)

X_DiabMed_race_train, X_DiabMed_race_val, y_DiabMed_race_train, y_DiabMed_race_val = train_test_split(X_Diab_Med_race_train, y_Diab_Med_race_train, test_size=0.2, random_state=1)

In [67]:
X_DiabMed_race_train.head()

race
40985   2.0
38441   2.0
42042   2.0
69887   2.0
73154   2.0

In [68]:
y_DiabMed_race_train.head()

num_medications
40985               22
38441               14
42042               18
69887               14
73154               15

In [69]:
np.mean(X_DiabMed_race_train)

race    2.126288
dtype: float64

In [70]:
np.mean(y_DiabMed_race_train)

num_medications    16.010594
dtype: float64

In [72]:
# Logistic Regression for 'race' X_DiabMed_race_train, y_DiabMed_race_train
logr = LogisticRegression(C=1000, max_iter = 100)
logr.fit(X_DiabMed_race_train, y_DiabMed_race_train)

/Users/edk/anaconda3/envs/metis/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/edk/anaconda3/envs/metis/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(C=1000)

In [76]:
# # F1 precision_score(y_change1_train, y_predict), recall_score(y_change1_train, y_predict)

# # recall (y_true)
# recall = y_DiabMed_race_train

# # predict (y_pred)
# predict = y_predict

# # calculate F1 score
# f1_score(recall, predict)

In [74]:
# Random Forest for race X_DiabMed_race_train, y_DiabMed_race_train
from sklearn.ensemble import RandomForestClassifier
RC = RandomForestClassifier(n_estimators = 100)
RC.fit(X_DiabMed_race_train, y_DiabMed_race_train)
y_RC_TRAIN_predict = RC.predict(X_DiabMed_race_train)

print("Accuracy:",metrics.accuracy_score(y_DiabMed_race_train, y_RC_TRAIN_predict))

/var/folders/0b/2h06wtt932j8vbn2kb4_x_2w0000gn/T/ipykernel_3934/3381765837.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  RC.fit(X_DiabMed_race_train, y_DiabMed_race_train)


Accuracy: 0.060157533510417784


# Race (Test)

In [75]:
# Logistic Regression for 'race' # X_Diab_Med_race_test, y_Diab_Med_race_test
logr = LogisticRegression(C=1000)
logr.fit(X_Diab_Med_race_test, y_Diab_Med_race_test)

/Users/edk/anaconda3/envs/metis/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/edk/anaconda3/envs/metis/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(C=1000)

In [77]:
logr.score(X_Diab_Med_race_test, y_Diab_Med_race_test)

0.06116733811535816

In [78]:
logr.coef_, logr.intercept_

(array([[-0.23955639],
        [ 0.29399339],
        [ 0.36130347],
        [ 0.09782672],
        [ 0.15771564],
        [ 0.17624543],
        [ 0.19832446],
        [ 0.17084482],
        [ 0.11949366],
        [ 0.29290541],
        [ 0.08640277],
        [ 0.20312023],
        [ 0.09577835],
        [ 0.09390662],
        [ 0.1164455 ],
        [ 0.08929911],
        [ 0.11689154],
        [ 0.18051095],
        [ 0.04200706],
        [ 0.08171899],
        [ 0.1797632 ],
        [ 0.16289624],
        [ 0.14835844],
        [ 0.14327651],
        [ 0.12617538],
        [ 0.17765148],
        [ 0.19932267],
        [ 0.18958167],
        [ 0.03509653],
        [ 0.24780376],
        [ 0.09901782],
        [ 0.15049497],
        [ 0.29429587],
        [ 0.27722031],
        [ 0.38942477],
        [ 0.44828233],
        [-0.00162189],
        [-0.20689142],
        [ 0.4758869 ],
        [ 0.11677461],
        [ 0.16375586],
        [ 0.15197167],
        [ 0.18628125],
        [ 0

In [81]:
# precision_score and recall_score # X_Diab_Med_race_test, y_Diab_Med_race_test
y_predict = logr.predict(X_Diab_Med_race_test)
print ("Precision: {:6.4f}, Recall: {:6.4f}".format(precision_score(y_Diab_Med_race_test, y_predict, average = 'micro'), recall_score(y_Diab_Med_race_test, y_predict, average = 'micro')))

Precision: 0.0612, Recall: 0.0612


In [ ]:
# F1 precision_score(y_change1_train, y_predict), recall_score(y_change1_train, y_predict)

# recall (y_true)
recall = y_Diab_Med_race_test

# predict (y_pred)
predict = y_predict

# calculate F1 score
f1_score(recall, predict)

In [79]:
# Random Forest for  # X_Diab_Med_race_test, y_Diab_Med_race_test
from sklearn.ensemble import RandomForestClassifier
RC = RandomForestClassifier(n_estimators = 100)
RC.fit(X_Diab_Med_race_test, y_Diab_Med_race_test)
y_RC_predict = RC.predict(X_Diab_Med_race_test)

print("Accuracy:",metrics.accuracy_score(y_Diab_Med_race_test, y_RC_predict))

/var/folders/0b/2h06wtt932j8vbn2kb4_x_2w0000gn/T/ipykernel_3934/4038783451.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  RC.fit(X_Diab_Med_race_test, y_Diab_Med_race_test)


Accuracy: 0.06190429399626609
